# Версии библиотек
[versions] #— здесь указываются версии зависимостей и плагинов.
spring-boot = "3.4.0"
spring-dependency-management = "1.1.6"
spotbugs = "6.0.26"
lombok = "1.18.36"
junit-jupiter = "5.10.0"
assertj = "3.24.2"
junit-platform = "1.10.0"

[libraries] #— здесь описываются библиотеки и их версии.
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

[bundles] #— здесь можно группировать несколько зависимостей вместе.

[plugins] #— здесь указываются плагины и их версии
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }