--liquibase formatted sql

--changeset petrarsentev:create_table_calc_events runOnChange:false
CREATE TABLE public.calc_events (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   first INTEGER,
   second INTEGER,
   result INTEGER,
   create_date TIMESTAMP WITHOUT TIME ZONE,
   type VARCHAR(255),
   CONSTRAINT pk_calc_events PRIMARY KEY (id)
);

ALTER TABLE public.calc_events ADD CONSTRAINT FK_CALC_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES public.users (id);

--rollback DROP TABLE IF EXISTS public.calc_events;